import React from 'react';
import { View, Text, Modal, TouchableOpacity, TouchableWithoutFeedback, Linking, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

export const SettingsModal = ({ visible, onClose, styles }) => {
  return (
    <Modal
      visible={visible}
      animationType="none"
      transparent={true}
      onRequestClose={onClose}
    >
      <TouchableWithoutFeedback onPress={onClose}>
        <View style={styles.settingsModalOverlay}>
          <TouchableWithoutFeedback onPress={(e) => e.stopPropagation()}>
            <View style={styles.settingsModalContent}>
              <Text style={styles.settingsModalTitle}>Settings</Text>

              {/* AI Translation Disclaimer */}
              <View style={localStyles.section}>
                <View style={localStyles.disclaimerBox}>
                  <Ionicons name="information-circle" size={20} color="#007AFF" />
                  <Text style={localStyles.disclaimerText}>
                    Word translations are generated by AI and may not be accurate. They are provided as a learning aid.
                  </Text>
                </View>
              </View>

              <Text style={styles.settingsModalText}>
                If you enjoy the app you can leave an optional tip!
              </Text>
              <TouchableOpacity
                style={styles.venmoButton}
                onPress={() => Linking.openURL('venmo://paycharge?txn=pay&recipients=EthanHoppe').catch(() =>
                  Linking.openURL('https://venmo.com/u/EthanHoppe')
                )}
              >
                <Text style={styles.venmoButtonText}>Tip on Venmo</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.paypalButton}
                onPress={() => Linking.openURL('https://paypal.me/ethandhoppe')}
              >
                <Text style={styles.paypalButtonText}>Tip on PayPal</Text>
              </TouchableOpacity>
              <View style={styles.feedbackSection}>
                <Text style={styles.settingsModalText}>Leave feedback or comments:</Text>
                <TouchableOpacity
                  style={styles.emailLink}
                  onPress={() => Linking.openURL('mailto:ethan@ingenuitylabs.net')}
                >
                  <Text style={styles.emailText}>ethan@ingenuitylabs.net</Text>
                </TouchableOpacity>
              </View>
              <TouchableOpacity
                style={styles.settingsModalButton}
                onPress={onClose}
              >
                <Text style={styles.settingsModalButtonText}>Close</Text>
              </TouchableOpacity>
            </View>
          </TouchableWithoutFeedback>
        </View>
      </TouchableWithoutFeedback>
    </Modal>
  );
};

const localStyles = StyleSheet.create({
  section: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
  },
  disclaimerBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#F0F8FF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B3D9FF',
  },
  disclaimerText: {
    flex: 1,
    fontSize: 13,
    color: '#1A1A1A',
    lineHeight: 18,
  },
});
