import React from 'react';
import { View, Text, Modal, TouchableOpacity, TouchableWithoutFeedback, Linking, StyleSheet, Switch } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

export const SettingsModal = ({ visible, onClose, styles, showFlashcardWords, onToggleFlashcardWords }) => {
  return (
    <Modal
      visible={visible}
      animationType="none"
      transparent={true}
      onRequestClose={onClose}
    >
      <TouchableWithoutFeedback onPress={onClose}>
        <View style={styles.settingsModalOverlay}>
          <TouchableWithoutFeedback onPress={(e) => e.stopPropagation()}>
            <View style={styles.settingsModalContent}>
              <Text style={styles.settingsModalTitle}>Settings</Text>

              {/* Show Flashcard Words Toggle */}
              <View style={localStyles.settingRow}>
                <View style={localStyles.settingTextContainer}>
                  <Text style={localStyles.settingLabel}>Highlight Flashcard Words</Text>
                  <Text style={localStyles.settingDescription}>
                    Show words already in your flashcards with a green highlight
                  </Text>
                </View>
                <Switch
                  value={showFlashcardWords}
                  onValueChange={onToggleFlashcardWords}
                  trackColor={{ false: '#E5E5EA', true: '#34C759' }}
                  thumbColor="#fff"
                />
              </View>

              {/* AI Translation Disclaimer */}
              <View style={localStyles.section}>
                <View style={localStyles.disclaimerBox}>
                  <Ionicons name="information-circle" size={20} color="#007AFF" />
                  <Text style={localStyles.disclaimerText}>
                    Word translations are generated by AI. New Testament translations are mostly accurate, but Old Testament translations may have errors. They are provided as a learning aid.
                  </Text>
                </View>
              </View>

              <View style={styles.feedbackSection}>
                <Text style={styles.settingsModalText}>Leave feedback or comments:</Text>
                <TouchableOpacity
                  style={styles.emailLink}
                  onPress={() => Linking.openURL('mailto:ethan@ingenuitylabs.net')}
                >
                  <Text style={styles.emailText}>ethan@ingenuitylabs.net</Text>
                </TouchableOpacity>
              </View>
              <TouchableOpacity
                style={styles.settingsModalButton}
                onPress={onClose}
              >
                <Text style={styles.settingsModalButtonText}>Close</Text>
              </TouchableOpacity>
            </View>
          </TouchableWithoutFeedback>
        </View>
      </TouchableWithoutFeedback>
    </Modal>
  );
};

const localStyles = StyleSheet.create({
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
  },
  settingTextContainer: {
    flex: 1,
    marginRight: 12,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 2,
  },
  settingDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  section: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
  },
  disclaimerBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#F0F8FF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#B3D9FF',
  },
  disclaimerText: {
    flex: 1,
    fontSize: 13,
    color: '#1A1A1A',
    lineHeight: 18,
  },
});
