import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  headerBar: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 25,
    left: 16,
    right: 16,
    zIndex: 1000,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // Liquid Glass capsules for the floating header controls.
  glassCapsule: {
    borderRadius: 22,
    minHeight: 44,
    justifyContent: 'center',
  },
  glassButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  glassIconButton: {
    width: 40,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Long book names shrink (and truncate) before pushing the header buttons off screen.
  referenceCapsule: {
    flexShrink: 1,
    marginRight: 8,
  },
  referenceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
  },
  referenceText: {
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    marginRight: 4,
  },
  flashcardsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  flashcardsButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    marginLeft: 4,
  },
  headerRightButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  translationButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minWidth: 36,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  headerButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  wordsCountButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minWidth: 44,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  wordsCountText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text,
    textAlign: 'center',
  },
  content: {
    flex: 1,
  },
  storyContent: {
    width: '100%',
    alignSelf: 'center',
    padding: 24,
    paddingTop: 70,
    paddingBottom: 0,
  },
  storyTitle: {
    ...theme.arabic.large,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  storyTitleEnglish: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 32,
    fontStyle: 'italic',
  },
  verseContainer: {
    marginBottom: 24,
  },
  // The passage opened from a Gathering link.
  linkedVerse: {
    backgroundColor: theme.colors.surfaceOverlay,
    borderRadius: 10,
    marginHorizontal: -8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  paragraphWithNumber: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  paragraph: {
    flex: 1,
  },
  arabicText: {
    ...theme.arabic.body,
    color: theme.colors.text,
  },
  arabicVerse: {
    ...theme.arabic.body,
    color: theme.colors.text,
    textAlign: 'right',
  },
  activeWordContainer: {
    backgroundColor: theme.colors.primary,
  },
  activeWordText: {
    color: theme.colors.textOnPrimary,
  },
  savedWordContainer: {
    backgroundColor: theme.colors.savedWordBackground,
  },
  savedWordText: {
    color: theme.colors.text,
  },
  flashcardWordContainer: {
    backgroundColor: theme.colors.flashcardWordBackground,
  },
  tooltipText: {
    fontSize: 18,
    color: theme.colors.text,
    fontWeight: '600',
    textAlign: 'center',
    flexShrink: 0,
  },
  verseNumber: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    minWidth: 20,
    textAlign: 'left',
  },
  verseNumberTouchable: {
    position: 'relative',
    marginLeft: 12,
    marginTop: 5,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 6,
    minWidth: 28,
  },
  bookmarkedVerseText: {
    color: theme.colors.primary,
    fontWeight: '600',
  },
  bookmarkIcon: {
    position: 'absolute',
    right: -2,
    top: 6,
  },
  englishText: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    fontWeight: '400',
    textAlign: 'left',
    marginTop: 8,
    marginBottom: 8,
    fontStyle: 'italic',
  },
  // Tablet layout: English on the left, Arabic on the right, in one row per verse.
  sideBySideRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 32,
  },
  sideBySideColumn: {
    flex: 1,
  },
  englishSideBySide: {
    fontSize: 17,
    lineHeight: 27,
    // Arabic lines are taller (harakat); nudge English down so first lines align.
    marginTop: 6,
    marginBottom: 0,
  },
  // "Back to Gathering", floating above the saved-words button.
  gatheringReturnRow: {
    position: 'absolute',
    bottom: 112,
    left: 16,
    right: 16,
    alignItems: 'center',
  },
  gatheringReturnPill: {
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: '100%',
    borderRadius: 22,
    minHeight: 44,
  },
  gatheringReturnPressable: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    minHeight: 44,
    paddingLeft: 12,
    paddingRight: 4,
    gap: 4,
  },
  gatheringReturnText: {
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.info,
  },
  gatheringReturnDismiss: {
    minHeight: 44,
    paddingLeft: 6,
    paddingRight: 14,
    justifyContent: 'center',
  },
  // Small round button in the bottom-left corner, with the count as a badge.
  savedWordsButton: {
    position: 'absolute',
    left: 20,
    bottom: 46,
    width: 52,
    height: 52,
  },
  savedWordsGlass: {
    flex: 1,
    borderRadius: 26,
  },
  savedWordsPressable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedWordsBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  savedWordsBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textOnPrimary,
  },
  // "Next: Book N" at the end of a chapter's text.
  nextChapterLink: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 4,
    marginTop: 32,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  nextChapterText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.info,
  },
  // Chapter selector modal styles
  selectorOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  selectorContent: {
    backgroundColor: theme.colors.surfaceElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '80%',
  },
  selectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  selectorTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  cancelButton: {
    padding: 8,
  },
  cancelButtonText: {
    fontSize: 16,
    color: theme.colors.primary,
    fontWeight: '500',
  },
  bookRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  bookRowExpanded: {
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 0,
  },
  bookName: {
    fontSize: 18,
    fontWeight: '500',
    color: theme.colors.text,
  },
  bookNameExpanded: {
    fontWeight: '700',
  },
  chapterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  chapterButton: {
    width: '20%',
    aspectRatio: 1,
    padding: 4,
  },
  chapterButtonInner: {
    flex: 1,
    backgroundColor: theme.colors.cardBackground,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  chapterButtonCurrent: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  chapterNumber: {
    fontSize: 18,
    fontWeight: '500',
    color: theme.colors.text,
  },
  chapterNumberCurrent: {
    color: theme.colors.textOnPrimary,
  },
  // Saved words modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: theme.colors.surfaceElevated,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  closeButton: {
    padding: 8,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.primary,
  },
  editHint: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    paddingHorizontal: 24,
    paddingBottom: 8,
    fontStyle: 'italic',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 12,
    gap: 8,
  },
  addToFlashcardsButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
  },
  addToFlashcardsButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.textOnPrimary,
  },
  clearAllButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: theme.colors.burgundy,
  },
  clearAllButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.white,
  },
  savedWordsList: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 24,
  },
  wordCount: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 16,
  },
  savedWordItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  wordContent: {
    flex: 1,
  },
  savedWordArabic: {
    ...theme.arabic.small,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 4,
  },
  savedWordEnglish: {
    fontSize: 16,
    color: theme.colors.primary,
  },
  translationInput: {
    fontSize: 16,
    color: theme.colors.primary,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 2,
  },
  savedWordReference: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontStyle: 'italic',
    marginTop: 2,
  },
  translateButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  removeWordButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.burgundy,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  removeWordText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.white,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  emptyText: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: theme.colors.textSecondary,
  },
  settingsModalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsModalContent: {
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: 16,
    padding: 24,
    marginHorizontal: 32,
    maxWidth: 400,
    width: '85%',
    maxHeight: '80%',
  },
  settingsModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 16,
  },
  settingsModalText: {
    fontSize: 16,
    color: theme.colors.text,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 4,
  },
  settingsModalButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
  },
  settingsModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textOnPrimary,
  },
  feedbackSection: {
    marginBottom: 16,
    alignItems: 'center',
  },
  feedbackLabel: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 8,
    textAlign: 'center',
  },
  emailLink: {
    padding: 8,
    alignSelf: 'center',
  },
  emailText: {
    fontSize: 16,
    color: theme.colors.primary,
    textDecorationLine: 'underline',
  },
});
