#!/usr/bin/env python3
"""Complete Psalm 119 mapping merge script - adds remaining verses to partial file."""
import json

# Load current partial (has 1-70, 91-120)
with open('scripts/psalm119_partial.json', 'r') as f:
    data = json.load(f)

print(f"Starting with {len(data['verses'])} verses")

# Add remaining verses 71-90
# These are embedded from agent output
verses_71_90 = {
  "71": {"ar": "كَانَ مَا ذُقْتُ مِنْ هَوَانٍ لِخَيْرِي فَتَعَلَّمْتُ فَرَائِضَكَ.", "en": "It was good for me to be afflicted so that I might learn your decrees.", "mappings": [{"ar": "كَانَ", "en": "It was", "start": 0, "end": 5}, {"ar": "مَا", "en": "to be afflicted", "start": 6, "end": 9}, {"ar": "ذُقْتُ", "en": "to be afflicted", "start": 10, "end": 16}, {"ar": "مِنْ", "en": "to be afflicted", "start": 17, "end": 21}, {"ar": "هَوَانٍ", "en": "to be afflicted", "start": 22, "end": 29}, {"ar": "لِخَيْرِي", "en": "good for me", "start": 30, "end": 39}, {"ar": "فَتَعَلَّمْتُ", "en": "so that I might learn", "start": 40, "end": 52}, {"ar": "فَرَائِضَكَ.", "en": "your decrees.", "start": 53, "end": 65}]},
  "72": {"ar": "شَرِيعَةُ فَمِكَ خَيْرٌ لِي مِنْ كُلِّ ذَهَبِ الْعَالَمِ وَفِضَّتِهِ.", "en": "The law from your mouth is more precious to me than thousands of pieces of silver and gold.", "mappings": [{"ar": "شَرِيعَةُ", "en": "The law", "start": 0, "end": 9}, {"ar": "فَمِكَ", "en": "from your mouth", "start": 10, "end": 16}, {"ar": "خَيْرٌ", "en": "is more precious", "start": 17, "end": 24}, {"ar": "لِي", "en": "to me", "start": 25, "end": 28}, {"ar": "مِنْ", "en": "than", "start": 29, "end": 33}, {"ar": "كُلِّ", "en": "thousands of pieces of", "start": 34, "end": 39}, {"ar": "ذَهَبِ", "en": "gold.", "start": 40, "end": 46}, {"ar": "الْعَالَمِ", "en": "thousands of pieces of", "start": 47, "end": 57}, {"ar": "وَفِضَّتِهِ.", "en": "silver and", "start": 58, "end": 69}]},
  "73": {"ar": "يَدَاكَ صَنَعَتَانِي وَكَوَّنَتَانِي، فَهَبْنِي فَهْماً لأَتَعَلَّمَ وَصَايَاكَ.", "en": "Your hands made me and formed me; give me understanding to learn your commands.", "mappings": [{"ar": "يَدَاكَ", "en": "Your hands", "start": 0, "end": 7}, {"ar": "صَنَعَتَانِي", "en": "made me", "start": 8, "end": 19}, {"ar": "وَكَوَّنَتَانِي،", "en": "and formed me;", "start": 20, "end": 35}, {"ar": "فَهَبْنِي", "en": "give me", "start": 36, "end": 45}, {"ar": "فَهْماً", "en": "understanding", "start": 46, "end": 53}, {"ar": "لأَتَعَلَّمَ", "en": "to learn", "start": 54, "end": 65}, {"ar": "وَصَايَاكَ.", "en": "your commands.", "start": 66, "end": 77}]},
  "74": {"ar": "فَيَرَانِي مُتَّقُوكَ وَيَفْرَحُونَ، لأَنِّي انْتَظَرْتُ كَلامَكَ.", "en": "May those who fear you rejoice when they see me, for I have put my hope in your word.", "mappings": [{"ar": "فَيَرَانِي", "en": "when they see me,", "start": 0, "end": 10}, {"ar": "مُتَّقُوكَ", "en": "May those who fear you", "start": 11, "end": 21}, {"ar": "وَيَفْرَحُونَ،", "en": "rejoice", "start": 22, "end": 35}, {"ar": "لأَنِّي", "en": "for I", "start": 36, "end": 43}, {"ar": "انْتَظَرْتُ", "en": "have put my hope in", "start": 44, "end": 55}, {"ar": "كَلامَكَ.", "en": "your word.", "start": 56, "end": 65}]},
  "75": {"ar": "قَدْ عَلِمْتُ يَا رَبُّ أَنَّ أَحْكَامَكَ عَادِلَةٌ، وَأَنَّكَ بِالْحَقِّ أَدَّبْتَنِي.", "en": "I know, Lord, that your laws are righteous, and that in faithfulness you have afflicted me.", "mappings": [{"ar": "قَدْ", "en": "I know,", "start": 0, "end": 4}, {"ar": "عَلِمْتُ", "en": "I know,", "start": 5, "end": 13}, {"ar": "يَا", "en": "Lord,", "start": 14, "end": 17}, {"ar": "رَبُّ", "en": "Lord,", "start": 18, "end": 23}, {"ar": "أَنَّ", "en": "that", "start": 24, "end": 29}, {"ar": "أَحْكَامَكَ", "en": "your laws", "start": 30, "end": 41}, {"ar": "عَادِلَةٌ،", "en": "are righteous,", "start": 42, "end": 52}, {"ar": "وَأَنَّكَ", "en": "and that", "start": 53, "end": 62}, {"ar": "بِالْحَقِّ", "en": "in faithfulness", "start": 63, "end": 73}, {"ar": "أَدَّبْتَنِي.", "en": "you have afflicted me.", "start": 74, "end": 86}]},
  "76": {"ar": "فَلْتَكُنْ رَحْمَتُكَ تَعْزِيَةً لِي، بِمُقْتَضَى وَعْدِكَ لِعَبْدِكَ.", "en": "May your unfailing love be my comfort, according to your promise to your servant.", "mappings": [{"ar": "فَلْتَكُنْ", "en": "May be", "start": 0, "end": 10}, {"ar": "رَحْمَتُكَ", "en": "your unfailing love", "start": 11, "end": 21}, {"ar": "تَعْزِيَةً", "en": "my comfort,", "start": 22, "end": 32}, {"ar": "لِي،", "en": "my comfort,", "start": 33, "end": 37}, {"ar": "بِمُقْتَضَى", "en": "according to", "start": 38, "end": 49}, {"ar": "وَعْدِكَ", "en": "your promise", "start": 50, "end": 58}, {"ar": "لِعَبْدِكَ.", "en": "to your servant.", "start": 59, "end": 69}]},
  "77": {"ar": "لِتَأْتِنِي مَرَاحِمُكَ فَأَحْيَا، لأَنَّ شَرِيعَتَكَ هِيَ مُتْعَتِي.", "en": "Let your compassion come to me that I may live, for your law is my delight.", "mappings": [{"ar": "لِتَأْتِنِي", "en": "Let come to me", "start": 0, "end": 11}, {"ar": "مَرَاحِمُكَ", "en": "your compassion", "start": 12, "end": 23}, {"ar": "فَأَحْيَا،", "en": "that I may live,", "start": 24, "end": 34}, {"ar": "لأَنَّ", "en": "for", "start": 35, "end": 41}, {"ar": "شَرِيعَتَكَ", "en": "your law", "start": 42, "end": 53}, {"ar": "هِيَ", "en": "is", "start": 54, "end": 58}, {"ar": "مُتْعَتِي.", "en": "my delight.", "start": 59, "end": 69}]},
  "78": {"ar": "لِيَخْزَ الْمُتَكَبِّرُونَ لأَنَّهُمُ افْتَرَوْا عَلَيَّ زُوراً، أَمَّا أَنَا فَأَتَأَمَّلُ فِي وَصَايَاكَ.", "en": "May the arrogant be put to shame for wronging me without cause; but I will meditate on your precepts.", "mappings": [{"ar": "لِيَخْزَ", "en": "May be put to shame", "start": 0, "end": 8}, {"ar": "الْمُتَكَبِّرُونَ", "en": "the arrogant", "start": 9, "end": 25}, {"ar": "لأَنَّهُمُ", "en": "for", "start": 26, "end": 36}, {"ar": "افْتَرَوْا", "en": "wronging", "start": 37, "end": 47}, {"ar": "عَلَيَّ", "en": "me", "start": 48, "end": 55}, {"ar": "زُوراً،", "en": "without cause;", "start": 56, "end": 64}, {"ar": "أَمَّا", "en": "but", "start": 65, "end": 71}, {"ar": "أَنَا", "en": "I", "start": 72, "end": 77}, {"ar": "فَأَتَأَمَّلُ", "en": "will meditate", "start": 78, "end": 90}, {"ar": "فِي", "en": "on", "start": 91, "end": 95}, {"ar": "وَصَايَاكَ.", "en": "your precepts.", "start": 96, "end": 107}]},
  "79": {"ar": "لِيَنْضَمَّ إِلَيَّ مُتَّقُوكَ وَعَارِفُو شَهَادَاتِكَ.", "en": "May those who fear you turn to me, those who understand your statutes.", "mappings": [{"ar": "لِيَنْضَمَّ", "en": "May turn", "start": 0, "end": 11}, {"ar": "إِلَيَّ", "en": "to me,", "start": 12, "end": 19}, {"ar": "مُتَّقُوكَ", "en": "those who fear you", "start": 20, "end": 30}, {"ar": "وَعَارِفُو", "en": "those who understand", "start": 31, "end": 41}, {"ar": "شَهَادَاتِكَ.", "en": "your statutes.", "start": 42, "end": 55}]},
  "80": {"ar": "لِيَكُنْ قَلْبِي مُتَعَلِّقاً بِكَامِلِ فَرَائِضِكَ، فَلَا أَخْزَى.", "en": "May I wholeheartedly follow your decrees, that I may not be put to shame.", "mappings": [{"ar": "لِيَكُنْ", "en": "May", "start": 0, "end": 8}, {"ar": "قَلْبِي", "en": "I wholeheartedly", "start": 9, "end": 16}, {"ar": "مُتَعَلِّقاً", "en": "follow", "start": 17, "end": 29}, {"ar": "بِكَامِلِ", "en": "wholeheartedly", "start": 30, "end": 39}, {"ar": "فَرَائِضِكَ،", "en": "your decrees,", "start": 40, "end": 52}, {"ar": "فَلَا", "en": "that I may not", "start": 53, "end": 59}, {"ar": "أَخْزَى.", "en": "be put to shame.", "start": 60, "end": 68}]},
  "81": {"ar": "تَتَلَهَّفُ نَفْسِي إِلَى خَلاصِكَ. رَجَائِي هُوَ كَلِمَتُكَ.", "en": "My soul faints with longing for your salvation, but I have put my hope in your word.", "mappings": [{"ar": "تَتَلَهَّفُ", "en": "faints with longing", "start": 0, "end": 11}, {"ar": "نَفْسِي", "en": "My soul", "start": 12, "end": 19}, {"ar": "إِلَى", "en": "for", "start": 20, "end": 26}, {"ar": "خَلاصِكَ.", "en": "your salvation,", "start": 27, "end": 36}, {"ar": "رَجَائِي", "en": "but I have put my hope", "start": 37, "end": 45}, {"ar": "هُوَ", "en": "in", "start": 46, "end": 50}, {"ar": "كَلِمَتُكَ.", "en": "your word.", "start": 51, "end": 62}]},
  "82": {"ar": "كَلَّتْ عَيْنَايَ فِي انْتِظَارِ كَلامِكَ، وَأَنَا أَقُولُ: مَتَى تُعَزِّينِي؟", "en": "My eyes fail, looking for your promise; I say, \"When will you comfort me?\"", "mappings": [{"ar": "كَلَّتْ", "en": "fail,", "start": 0, "end": 7}, {"ar": "عَيْنَايَ", "en": "My eyes", "start": 8, "end": 17}, {"ar": "فِي", "en": "looking for", "start": 18, "end": 22}, {"ar": "انْتِظَارِ", "en": "looking for", "start": 23, "end": 33}, {"ar": "كَلامِكَ،", "en": "your promise;", "start": 34, "end": 43}, {"ar": "وَأَنَا", "en": "I", "start": 44, "end": 51}, {"ar": "أَقُولُ:", "en": "say,", "start": 52, "end": 60}, {"ar": "مَتَى", "en": "\"When", "start": 61, "end": 66}, {"ar": "تُعَزِّينِي؟", "en": "will you comfort me?\"", "start": 67, "end": 79}]},
  "83": {"ar": "أَصْبَحْتُ كَقِرْبَةِ خَمْرٍ أَتْلَفَتْهَا الْحَرَارَةُ وَالدُّخَانُ، وَلَكِنِّي لَمْ أَنْسَ فَرَائِضَكَ.", "en": "Though I am like a wineskin in the smoke, I do not forget your decrees.", "mappings": [{"ar": "أَصْبَحْتُ", "en": "Though I am", "start": 0, "end": 10}, {"ar": "كَقِرْبَةِ", "en": "like a wineskin", "start": 11, "end": 21}, {"ar": "خَمْرٍ", "en": "wineskin", "start": 22, "end": 28}, {"ar": "أَتْلَفَتْهَا", "en": "in", "start": 29, "end": 41}, {"ar": "الْحَرَارَةُ", "en": "in", "start": 42, "end": 53}, {"ar": "وَالدُّخَانُ،", "en": "the smoke,", "start": 54, "end": 67}, {"ar": "وَلَكِنِّي", "en": "I do", "start": 68, "end": 78}, {"ar": "لَمْ", "en": "not", "start": 79, "end": 83}, {"ar": "أَنْسَ", "en": "forget", "start": 84, "end": 90}, {"ar": "فَرَائِضَكَ.", "en": "your decrees.", "start": 91, "end": 103}]},
  "84": {"ar": "كَمْ هِي أَيَّامُ عُمْرِ عَبْدِكَ؟ مَتَى تُنْزِلُ الْقَضَاءَ بِالَّذِينَ يَضْطَهِدُونَنِي؟", "en": "How long must your servant wait? When will you punish my persecutors?", "mappings": [{"ar": "كَمْ", "en": "How long", "start": 0, "end": 4}, {"ar": "هِي", "en": "must", "start": 5, "end": 9}, {"ar": "أَيَّامُ", "en": "wait?", "start": 10, "end": 18}, {"ar": "عُمْرِ", "en": "wait?", "start": 19, "end": 25}, {"ar": "عَبْدِكَ؟", "en": "your servant", "start": 26, "end": 35}, {"ar": "مَتَى", "en": "When", "start": 36, "end": 41}, {"ar": "تُنْزِلُ", "en": "will you punish", "start": 42, "end": 51}, {"ar": "الْقَضَاءَ", "en": "will you punish", "start": 52, "end": 62}, {"ar": "بِالَّذِينَ", "en": "my persecutors?", "start": 63, "end": 74}, {"ar": "يَضْطَهِدُونَنِي؟", "en": "my persecutors?", "start": 75, "end": 91}]},
  "85": {"ar": "الْمُتَكَبِّرُونَ الَّذِينَ يَعْصَوْنَ شَرِيعَتَكَ حَفَرُوا لِي حُفَراً.", "en": "The arrogant dig pits to trap me, contrary to your law.", "mappings": [{"ar": "الْمُتَكَبِّرُونَ", "en": "The arrogant", "start": 0, "end": 16}, {"ar": "الَّذِينَ", "en": "contrary to", "start": 17, "end": 26}, {"ar": "يَعْصَوْنَ", "en": "contrary to", "start": 27, "end": 37}, {"ar": "شَرِيعَتَكَ", "en": "your law.", "start": 38, "end": 49}, {"ar": "حَفَرُوا", "en": "dig", "start": 50, "end": 58}, {"ar": "لِي", "en": "to trap me,", "start": 59, "end": 63}, {"ar": "حُفَراً.", "en": "pits", "start": 64, "end": 72}]},
  "86": {"ar": "وَصَايَاكَ كُلُّهَا صَادِقَةٌ. زُوراً يَضْطَهِدُونَنِي فَأَغِثْنِي.", "en": "All your commands are trustworthy; help me, for I am being persecuted without cause.", "mappings": [{"ar": "وَصَايَاكَ", "en": "your commands", "start": 0, "end": 10}, {"ar": "كُلُّهَا", "en": "All", "start": 11, "end": 19}, {"ar": "صَادِقَةٌ.", "en": "are trustworthy;", "start": 20, "end": 30}, {"ar": "زُوراً", "en": "without cause.", "start": 31, "end": 38}, {"ar": "يَضْطَهِدُونَنِي", "en": "for I am being persecuted", "start": 39, "end": 54}, {"ar": "فَأَغِثْنِي.", "en": "help me,", "start": 55, "end": 67}]},
  "87": {"ar": "لَوْلَا قَلِيلٌ لأَفْنَوْنِي مِنَ الأَرْضِ، لَكِنِّي لَمْ أَتْرُكْ شَرِيعَتَكْ.", "en": "They almost wiped me from the earth, but I have not forsaken your precepts.", "mappings": [{"ar": "لَوْلَا", "en": "They almost", "start": 0, "end": 7}, {"ar": "قَلِيلٌ", "en": "almost", "start": 8, "end": 16}, {"ar": "لأَفْنَوْنِي", "en": "wiped me", "start": 17, "end": 28}, {"ar": "مِنَ", "en": "from", "start": 29, "end": 34}, {"ar": "الأَرْضِ،", "en": "the earth,", "start": 35, "end": 44}, {"ar": "لَكِنِّي", "en": "but I", "start": 45, "end": 54}, {"ar": "لَمْ", "en": "have not", "start": 55, "end": 59}, {"ar": "أَتْرُكْ", "en": "forsaken", "start": 60, "end": 68}, {"ar": "شَرِيعَتَكْ.", "en": "your precepts.", "start": 69, "end": 81}]},
  "88": {"ar": "أَحْيِنِي بِمُقْتَضَى رَحْمَتِكَ، فَأُطِيعَ شَرَائِعَكَ.", "en": "In your unfailing love preserve my life, that I may obey the statutes of your mouth.", "mappings": [{"ar": "أَحْيِنِي", "en": "preserve my life,", "start": 0, "end": 9}, {"ar": "بِمُقْتَضَى", "en": "In", "start": 10, "end": 21}, {"ar": "رَحْمَتِكَ،", "en": "your unfailing love", "start": 22, "end": 33}, {"ar": "فَأُطِيعَ", "en": "that I may obey", "start": 34, "end": 43}, {"ar": "شَرَائِعَكَ.", "en": "the statutes of your mouth.", "start": 44, "end": 56}]},
  "89": {"ar": "يَا رَبُّ كَلِمَتُكَ تَدُومُ ثَابِتَةً فِي السَّمَاوَاتِ إِلَى الأَبَدِ.", "en": "Your word, Lord, is eternal; it stands firm in the heavens.", "mappings": [{"ar": "يَا", "en": "Lord,", "start": 0, "end": 3}, {"ar": "رَبُّ", "en": "Lord,", "start": 4, "end": 9}, {"ar": "كَلِمَتُكَ", "en": "Your word,", "start": 10, "end": 20}, {"ar": "تَدُومُ", "en": "is eternal;", "start": 21, "end": 28}, {"ar": "ثَابِتَةً", "en": "it stands firm", "start": 29, "end": 39}, {"ar": "فِي", "en": "in", "start": 40, "end": 44}, {"ar": "السَّمَاوَاتِ", "en": "the heavens.", "start": 45, "end": 57}, {"ar": "إِلَى", "en": "is eternal;", "start": 58, "end": 64}, {"ar": "الأَبَدِ.", "en": "is eternal;", "start": 65, "end": 74}]},
  "90": {"ar": "مِنْ جِيلٍ إِلَى جِيلٍ أَمَانَتُكَ. أَنْتَ أَسَّسْتَ الأَرْضَ فَلَنْ تَتَزَعْزَعَ.", "en": "Your faithfulness continues through all generations; you established the earth, and it endures.", "mappings": [{"ar": "مِنْ", "en": "through all generations;", "start": 0, "end": 4}, {"ar": "جِيلٍ", "en": "through all generations;", "start": 5, "end": 11}, {"ar": "إِلَى", "en": "through all generations;", "start": 12, "end": 18}, {"ar": "جِيلٍ", "en": "through all generations;", "start": 19, "end": 25}, {"ar": "أَمَانَتُكَ.", "en": "Your faithfulness continues", "start": 26, "end": 38}, {"ar": "أَنْتَ", "en": "you", "start": 39, "end": 45}, {"ar": "أَسَّسْتَ", "en": "established", "start": 46, "end": 55}, {"ar": "الأَرْضَ", "en": "the earth,", "start": 56, "end": 64}, {"ar": "فَلَنْ", "en": "and it endures.", "start": 65, "end": 71}, {"ar": "تَتَزَعْزَعَ.", "en": "and it endures.", "start": 72, "end": 84}]}
}

data['verses'].update(verses_71_90)
print(f"Added 71-90. Total: {len(data['verses'])}")

# Save progress
with open('scripts/psalm119_partial.json', 'w') as f:
    json.dump(data, f, ensure_ascii=False)

print(f"Saved. Current verses: {sorted([int(k) for k in data['verses'].keys()])[:10]}...")
print(f"Missing verses: {[i for i in range(1, 177) if str(i) not in data['verses']]}")
