#!/usr/bin/env python3
"""
Fix remaining empty translations in ROM and TIT by direct mapping.
"""

import json
from pathlib import Path

# Specific translations for remaining empty words
REMAINING_TRANSLATIONS = {
    # ROM chapter 1
    'كُلِّهِ.': 'all.',
    'لِي': 'for me',
    'أَتَوَقَّفُ': 'I cease',
    'ذِكْرِكُمْ': 'mentioning you',
    'آتِيَ': 'to come',
    'الْمُشْتَرَكِ،': 'mutual',
    'إِيمَانِكُمْ': 'your faith',
    'وَإِيمَانِي.': 'and my faith.',
    'الأُمَمِ': 'Gentiles',
    'الأُخْرَى،': 'other,',
    'كُنْتُ': 'I was',
    'أُعَاقُ': 'prevented',
    'أُبَشِّرَ': 'to preach',
    'بِالإِنْجِيلِ': 'the gospel',
    'بَيْنَكُمْ': 'among you',
    'أَنْتُمُ': 'you',
    'رُومَا.': 'Rome.',
    'لِلْيُونَانِيِّ.': 'to the Greek.',
    'حَدِّ': 'degree',
    'كُتِبَ:': 'written:',
    'بِاطِلاً،': 'futile,',
    'التَّمْيِيزِ': 'discernment',
    'يُشْكَرَ': 'to be thanked',
    'الْحَمَاقَةِ': 'foolishness',
    'يَفْنَى': 'perishable',
    'الطُّيُورِ': 'birds',
    'الزَّوَاحِفِ.': 'reptiles.',
    'الأَرْبَعِ': 'four',
    'النَّجَاسَةِ،': 'impurity,',
    'بِهَا': 'with it',
    'أَجْسَادَهُمْ': 'their bodies',
    'الْخَالِقِ،': 'Creator,',
    'الْمَخْلُوقَاتِ': 'creation',
    'الأَبَدِ.': 'forever.',
    'آمِين.': 'Amen.',
    'أَهْوَاءِ': 'passions',
    'الْعَارِ:': 'shame:',
    'إِنَاثَهُمْ': 'their females',
    'اسْتِعْمَالِهَا': 'its use',
    'الطَّبِيعِيَّةِ': 'natural',
    'اللّائِقَةِ.': 'proper.',
    'الذُّكُورُ': 'males',
    'اسْتِعْمَالِ': 'use',
    'الإِنَاثِ': 'females',
    'الْفَاحِشَةَ': 'shameful acts',
    'الذُّكُورِ': 'males',
    'بِالذُّكُورِ،': 'with males,',
    'الْجَزَاءَ': 'penalty',
    'أَنْفُسِهِمِ': 'in themselves',
    'أَبْقَوْهُ': 'they kept',
    'الأُمُورِ': 'things',
    'اللائِقَةِ،': 'proper,',
    'الْحَقَّ': 'truth',
    'الإِثْمِ': 'wickedness',
    'الطَّمَعِ': 'greed',
    'السُّوءِ': 'evil',
    'الْحَسَدِ': 'envy',
    'الْقَتْلِ': 'murder',
    'الْخِصَامِ': 'strife',
    'الْغِشِّ': 'deceit',
    'الْخُبْثِ': 'malice',
    'نَمَّامُونَ': 'gossips',
    'مُفْتَرُونَ': 'slanderers',
    'لِلّهِ': 'of God',
    'مُتَطَاوِلُونَ': 'insolent',
    'مُتَكَبِّرُونَ': 'arrogant',
    'مُتَفَاخِرُونَ': 'boastful',
    'مُبْتَكِرُونَ': 'inventors',
    'لِلْوَالِدَيْنِ': 'to parents',
    'عُهُودِهِمْ': 'their promises',
    'الْحَنَانَ': 'affection',
    'الرَّحْمَةَ': 'mercy',
    'الْعَادِلَ': 'righteous',
    'يَسْتَحِقُّونَ': 'deserve',
    'الْمَوْتَ': 'death',
    'النَّاسَ': 'people',
    'يَمْدَحُونَ': 'they approve',

    # TIT chapter 1
    'خَادِماً': 'servant',
    'رَسُولاً': 'apostle',
    'لِيَسُوعَ': 'of Jesus',
    'الرَّجَاءِ': 'hope',
    'الْحَيَاةَ': 'life',
    'الأَبَدِيَّةَ': 'eternal',
    'وَعَدَ': 'promised',
    'الْيَكْذِبَ': 'cannot lie',
    'الأَزَلِ،': 'before time began,',
    'الأَزْمِنَةِ': 'times',
    'الْمُحَدَّدَةِ': 'appointed',
    'بِالْكِرَازَةِ': 'through preaching',
    'الْمَوْكُولَةِ': 'entrusted',
    'مُخَلِّصِنَا.': 'our Savior.',
    'تِيطُسَ': 'Titus',
    'الْمُشْتَرَكِ:': 'common:',
    'وَالرَّبِّ': 'and Lord',
    'مُخَلِّصِنَا!': 'our Savior!',
    'مِنْهَا': 'there',
    'بَقِيَ': 'remains',
    'نَاقِصاً': 'lacking',
    'أُنَبِّهَكَ': 'I remind you',
    'الشُّيُوخِ': 'elders',
    'وُجِدَ': 'is',
    'وَاحِدَةٍ': 'one',
    'الْفَجُورِ': 'debauchery',
    'الْعِصْيَانِ.': 'disobedience.',
    'مُشْرِفاً': 'overseer',
    'وَكِيلاً،': 'steward,',
    'مُتَعَجْرِفاً': 'overbearing',
    'حَادَّ': 'quick-tempered',
    'الطَّبْعِ': 'temper',
    'سِكِّيراً': 'drunkard',
    'عَنِيفاً': 'violent',
    'مُتَهَافِتاً': 'greedy',
    'الْمَكَاسِبِ': 'gain',
    'الْخَسِيسَةِ،': 'dishonest,',
    'مُحِبّاً': 'hospitable',
    'لِلضُّيُوفِ': 'lover of',
    'لِلصَّلاحِ': 'what is good',
    'مُتَزِّناً': 'self-controlled',
    'بَارّاً': 'upright',
    'تَقِيّاً': 'holy',
    'مُنْضَبِطاً،': 'disciplined,',
    'مُتَمَسِّكاً': 'holding firmly',
    'الْمُوَافِقِ': 'in accordance with',
    'لِلتَّعْلِيمِ': 'the teaching',
    'قَادِراً': 'able',
    'يُشَجِّعَ': 'to encourage',
    'السَّلِيمِ': 'sound',
    'يُفْحِمَ': 'to refute',
    'الْمُعَارِضِينَ.': 'those who oppose it.',
    'الْعَاصِينَ': 'rebellious',
    '«أَمَّا': 'As for',
    'أَفْوَاهُهُمْ:': 'their mouths:',
    'يَجِبُ': 'must',
    'تَسْكِيتُهُمْ': 'be silenced',
    'لأَنَّهُمْ': 'because they',
    'يُفْسِدُونَ': 'are disrupting',
    'بُيُوتاً': 'households',
    'يُعَلِّمُونَ': 'by teaching',
    'يَحِقُّ': 'ought',
    'تَعْلِيمُهُ': 'to teach',
    'لأَجْلِ': 'for',
    'الْخَسِيسَةِ.': 'dishonest gain.',
    'أَنْبِيَائِهِمْ:': 'their own prophets:',
    '«الْكَرِيتِيُّونَ': 'Cretans',
    'كَذَّابُونَ': 'liars',
    'دَائِماً،': 'always,',
    'وُحُوشٌ': 'evil brutes',
    'شَرِسَةٌ': 'brutal',
    'بُطُونٌ': 'gluttons',
    'كَسَالَى!»': 'lazy!',
    'الشَّهَادَةُ': 'testimony',
    'صَحِيحَةٌ.': 'true.',
    'لِهَذَا': 'Therefore',
    'وَبِّخْهُمْ': 'rebuke them',
    'بِشِدَّةٍ': 'sharply',
    'لِيَتَعَافَوْا': 'so that they will be sound',
    'يُعِيرُونَ': 'paying attention',
    'انْتِبَاهاً': 'to',
    'لِخُرَافَاتٍ': 'to myths',
    'يَهُودِيَّةٍ': 'Jewish',
    'وَوَصَايَا': 'and commands',
    'الْمُنْحَرِفِينَ': 'those who reject',
    'الْحَقِّ.': 'the truth.',
    'الطَّاهِرِينَ،': 'the pure,',
    'طَاهِرٌ.': 'pure.',
    'الأَدْنَاسِ': 'defiled',
    'يَتَدَنَّسُ': 'is defiled',
    'عُقُولُهُمْ': 'their minds',
    'ضَمَائِرُهُمْ.': 'consciences.',
    'يَزْعُمُونَ': 'They claim',
    'أَنَّهُمْ': 'that they',
    'يَعْرِفُونَ': 'know',
    'أَعْمَالِهِمْ': 'their actions',
    'يُنْكِرُونَهُ': 'they deny him',
    'مَكْرُوهُونَ': 'detestable',
    'عَاصُونَ': 'disobedient',
    'رَافِضُونَ': 'unfit',
    'عَمَلٍ': 'work',
    'صَالِحٍ.': 'good.',

    # Additional ROM 1 words
    'أَجْسَادِهِنَّ': 'their bodies',
    'الْعُقُولُ': 'minds',
    'الْفَحْشَاءَ': 'wickedness',
    'الْمَخْلُوقَاتِ.': 'creation.',
    'الْمَوْتَ؛': 'death;',
    'الْمُبَارَكِ': 'blessed',
    'انْصَرَفُوا': 'they turned',
    'بَاتُوا': 'they became',
    'بَدَلَ': 'instead of',
    'بَيَّنَهُ': 'made it plain',
    'بَيْنَنَا.': 'among us.',
    'بَيْنَهُمْ.': 'among them.',
    'بِأَنَّهُمْ': 'that they',
    'بِالإِثْمِ.': 'by wickedness.',
    'بِالإِيمَانِ،': 'by faith,',
    'بِالطَّرِيقَةِ': 'in the way',
    'بِتَفْكِيرِهِمْ': 'in their thinking',
    'بِذُكُورٍ،': 'with males,',
    'بِطَرِيقَةٍ': 'in a way',
    'بِفَاعِلِيهَا.': 'who do them.',
    'بِهِمْ:': 'in them:',
    'تَبَرَّرَ': 'justified',
    'تَبَيَّنَ': 'is clearly seen',
    'تَحَوَّلْنَ': 'exchanged',
    'تَوْبِيخِهِمْ،': 'rebuking them,',
    'تُدْرِكُهُ': 'it perceives',
    'ثَرْثَارُونَ،': 'gossips,',
    'جَزِيرَةِ': 'island',
    'حَنَانَ،': 'affection,',
    'خَاصٌّ': 'special',
    'خِيَانَةِ': 'faithlessness',
    'دُونَ': 'without',
    'رُذِّلَتْ': 'rejected',
    'سَأَلُوهُ': 'they asked him',
    'شَهْوَتِهِمْ': 'their lust',
    'شِرْكِ': 'fellowship',
    'صَارُوا': 'they became',
    'صِنْعَةِ': 'handiwork',
    'عِبَادَتِهِ': 'worship of him',
    'عُذْرٌ': 'excuse',
    'عِوَضاً': 'instead',
    'غَبِيَّةً.': 'foolish.',
    'فَأَسْلَمَهُمُ': 'so God gave them over',
    'فَامْتَلَأُوا': 'they became filled',
    'فَقَدْ': 'for',
    'فَكَمَا': 'for just as',
    'قَادِرٌ': 'able',
    'قَوَّتُهُ': 'his power',
    'كَرِيتَ،': 'Crete,',
    'كَرِيتَ.': 'Crete.',
    'لأَنَّهُ': 'for',
    'لِتَقِفَ': 'to stand',
    'لِلْحِكْمَةِ.': 'for wisdom.',
    'لِلدِّيَانَةِ': 'of religion',
    'لِلْمُؤْمِنِينَ': 'to believers',
    'لِيَفْعَلُوا': 'to do',
    'مَحْبُوبُونَ': 'beloved',
    'مَخْزِيَّةٌ': 'shameful',
    'مَكْتُوباً': 'written',
    'مَلَكُوتِهِ': 'his kingdom',
    'مُتَزَمِّتُونَ': 'ungodly',
    'مُدَبِّرِينَ': 'sensible',
    'مُسْتَخِفِّينَ': 'despising',
    'مُشْتَعِلِينَ': 'inflamed',
    'مُشَقِّقُونَ،': 'troublemakers,',
    'نَجَاسَةِ': 'impurity',
    'نَظَرِيَّةٍ': 'view',
    'وَاحِدَةٍ،': 'one,',
    'وَالْحَيَوَانَاتِ': 'and animals',
    'وَالشَّرِّ.': 'and evil.',
    'وَكُلُّهُمْ': 'and all of them',
    'وَلِهَذَا': 'and for this reason',
    'يُقَدِّسُهَا': 'sanctifies it',
    'يَمْلأُونَ': 'they fill',

    # Final batch
    'رَحْمَةَ.': 'mercy.',
    'ضَلالِهِمْ.': 'their error.',
    'عُذْرٍ.': 'excuse.',
    'لَهُمْ.': 'to them.',
    'لِلطَّبِيعَةِ.': 'to nature.',
    'لِلْوَالِدَيْنِ.': 'to parents.',
    'مُظْلِماً.': 'dark.',
    'وَالزَّوَاحِفِ.': 'and reptiles.',
    'وَسُوءاً.': 'and evil.',
    'يَحْيَا».': 'will live."',
    'خَلْقِ': 'creation',
    'خِلالِ': 'through',
    'دَفَعَهُمْ': 'gave them over',
    'ذُكُوراً': 'males',
    'سَبِيلِ': 'way',
    'صَارَتْ': 'became',
    'طَائِعِينَ': 'obedient',
    'ظَاهِرٌ': 'evident',
    'عَاطِلٍ': 'worthless',
    'عُقُولَهُمْ': 'their minds',
    'عِصْيَانٍ': 'disobedience',
    'غَيْرِ': 'not',
    'فَاسْتَحَقُّوا': 'they deserved',
    'فَبِالإِيمَانِ': 'by faith',
    'فِيمَا': 'in what',
    'قَلْبُهُمْ': 'their heart',
    'كَلِمَتَهُ': 'his word',
    'كُنْ': 'be',
    'كِرِيتَ': 'Crete',
    'لِغَبَاوَتِهِ': 'for his foolishness',
    'لِلْعِيَانِ': 'plain',
    'لِيُهِينُوا': 'to dishonor',
    'مُخَالِفَةٍ': 'contrary',
    'مُعْتَرِفِينَ': 'acknowledging',
    'مُمَارَسَةِ': 'practice',
    'مُنْذُ': 'since',
    'مِنْهُمْ': 'of them',
    'مِنْهُمْ،': 'of them,',
    'نَفْسَهُ،': 'himself,',
    'وَإِثْمٍ': 'and wickedness',
    'وَحَسْبُ،': 'only,',
    'وَذَوَاتِ': 'and',
    'وَصَارَ': 'and became',
    'وَغَيْرُ': 'and not',
    'وَقَدْ': 'and indeed',
    'وَمَعَ': 'and with',
    'وَهُمْ': 'and they',
    'وَهُوَ': 'and he',
    'يَحْجُبُونَ': 'suppress',
    'يَسْتَوْجِبُونَ': 'deserve',
    'يَنَالُوا': 'receive',
    'يُدِيرُونَ': 'turn',
    'يُسَرُّونَ': 'approve of',
    'يُمَارِسُونَهَا': 'practice them',
}


def fix_remaining():
    """Fix remaining empty translations."""
    for book in ['ROM', 'TIT']:
        mappings_dir = Path(f'bible-translations/mappings/{book}')
        total_fixed = 0
        still_empty = 0

        print(f"\nFixing {book}:")

        for chapter_file in sorted(mappings_dir.glob('*.json'), key=lambda x: int(x.stem)):
            with open(chapter_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            modified = False
            chapter_fixed = 0

            for verse_num, verse_data in data['verses'].items():
                for m in verse_data['mappings']:
                    if not m.get('en', '').strip():
                        ar_word = m['ar']
                        if ar_word in REMAINING_TRANSLATIONS:
                            m['en'] = REMAINING_TRANSLATIONS[ar_word]
                            chapter_fixed += 1
                            modified = True
                        else:
                            still_empty += 1

            if modified:
                with open(chapter_file, 'w', encoding='utf-8') as f:
                    json.dump(data, f, ensure_ascii=False, indent=2)
                print(f"  Chapter {chapter_file.stem}: Fixed {chapter_fixed} translations")
                total_fixed += chapter_fixed

        print(f"  Total: {total_fixed} fixed, {still_empty} still empty")


if __name__ == "__main__":
    fix_remaining()
