import { StyleSheet } from 'react-native';

export const createWordStudyStyles = (theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    iconButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
    topTitle: { fontSize: 16, fontWeight: '600', color: theme.colors.text },
    header: { alignItems: 'center', paddingHorizontal: 20, paddingBottom: 12 },
    headword: { color: theme.colors.text, textAlign: 'center' },
    headGloss: { fontSize: 17, color: theme.colors.text, marginTop: 2 },
    count: { fontSize: 13, color: theme.colors.textSecondary, marginTop: 6 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 6, marginTop: 10 },
    chip: {
      backgroundColor: theme.colors.backgroundSecondary,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    chipText: { fontSize: 13, color: theme.colors.text },
    chipCount: { color: theme.colors.textSecondary },
    tabs: {
      flexDirection: 'row',
      marginHorizontal: 16,
      marginBottom: 4,
      backgroundColor: theme.colors.backgroundSecondary,
      borderRadius: 9,
      padding: 2,
    },
    tab: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 7 },
    tabActive: { backgroundColor: theme.colors.surfaceElevated, ...theme.shadows.sm },
    tabText: { fontSize: 14, color: theme.colors.textSecondary, fontWeight: '500' },
    tabTextActive: { color: theme.colors.text },
    listContent: { paddingHorizontal: 16, paddingBottom: 32 },
    row: {
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    rowHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
    reference: { fontSize: 14, fontWeight: '600', color: theme.colors.text },
    rowGloss: { fontSize: 13, color: theme.colors.textSecondary },
    relatedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
    },
    relatedText: { flex: 1, alignItems: 'flex-end' },
    relatedArabic: { color: theme.colors.text },
    hint: { fontSize: 13, color: theme.colors.textSecondary, paddingVertical: 10 },
    message: { fontSize: 14, color: theme.colors.textSecondary, textAlign: 'center', padding: 24 },
    spinner: { marginTop: 32 },
    moreButton: { alignItems: 'center', paddingVertical: 16 },
    moreText: { fontSize: 15, color: theme.colors.info, fontWeight: '500' },
  });
